#define MapEmpty 10
#define MapBlocked 14
#define MapTrap 18
#define MapGoalOne 22
#define MapGoalTwo 26
#define MapGoalThree 30
#define MapGoalFour 34
#define CommandUp 38
#define CommandRight 42
#define CommandLeft 46
#define CommandDown 50
#define CritterUp 1
#define CritterDown 2
#define CritterLeft 3
#define CritterRight 4
#define HazardUp 5
#define HazardDown 6
#define HazardLeft 7
#define HazardRight 8